# Este Archivo es parte del Framework Ocrend Moldeado Especialmente para esta StartUp(GetJob)
#
# (C) <f.andradevalenzuela@gmail.com>
#
# For the full copyright and license information, please view the LICENS
# file that was distributed with this source code.

# Conexi贸n con la base de datos principal
database:
  host: localhost
  user: root
  pass:
  name: getjob
  port: 1521
  protocol: TCP
  motor: mysql

# Configuraci贸n de servidor SMTP
phpmailer:
  host:
  user:
  pass:
  port: 465

# Configuraci贸n de sesiones
sessions:
  unique: 0CR3ND2017
  life_time: 3600

# Variables del framework
framework:
  debug: false
  version: 2.0.5

# Configuraci贸n del sitio
site:
  name: GetJob.cl
  author: Felipe Andrade
  author_email: f.andradevalenzuela@gmail.com
  timezone: America/Santiago
  url: http://localhost/getjob/
  router:
    path: localhost/getjob/
    protocol: http
